### ISSUE TITLE
现在市面上有适配著名厂家耗材的电动口罩了吗?

### ISSUE THREAD

**Issue by lb-chc** [kukela/kz#1]
项目很好, 我还见过一个兼容3M面罩和滤芯的套件(风机盒+软管+多个转接器), 但竟然要近1000块钱......我觉得这种东西是很能做开源硬件+3D打印的吧, 欧美国家应该尤其有这种兴趣的人, 但碍于英语水平, 机器翻译后也并没有搜索到相关信息, 想问一下你这边有没有了解

关于它的好处, 你想想理论上它可以让人呼吸到大指标符合三亚水平的空气, 作为日常出行用具的话有望消除汽车尾气的影响(如果能串联滤芯的话也许能), 并且电动送风才能解决长期跑步的呼吸需求, 甚至体弱者也可以使用高等级的防护用品了. 还有呼气水聚集于面罩的问题. 虽然这种用具很夸张, 但也算是在进行控制变量尝试, 通过相对廉价的方法改变了自己的生存环境不是吗?

感谢你看完

**Comment by kukela** [comment]
你好，目前我正计划做2.0版本，会解决目前版本的不少问题，但是目前还有其他项目在搞，预计2022年底会出来，你要是等不急，可以自己尝试做做看。

**Comment by lb-chc** [comment]
> 你好，现在我正计划做 2.0 版本，会解决当前版本的一些问题，目前还有其他项目在搞，感觉 202 2 年底会出来，你可能等不急，可以自己尝试做做。

https://github.com/jcl5m1/ventilator 我找到了
